Traceback (most recent call last):
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lukem/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/lukem/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# show all rows, all columns
pd.set_option("max_rows", None)
pd.set_option("max_columns", None)
pd.set_option('max_colwidth', None)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOptionError[0m                               Traceback (most recent call last)
Cell [0;32mIn[2], line 2[0m
[1;32m      1[0m [38;5;66;03m# show all rows, all columns[39;00m
[0;32m----> 2[0m pd[38;5;241m.[39mset_option([38;5;124m"[39m[38;5;124mmax_rows[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[1;32m      3[0m pd[38;5;241m.[39mset_option([38;5;124m"[39m[38;5;124mmax_columns[39m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[1;32m      4[0m pd[38;5;241m.[39mset_option([38;5;124m'[39m[38;5;124mmax_colwidth[39m[38;5;124m'[39m, [38;5;28;01mNone[39;00m)

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/_config/config.py:263[0m, in [0;36mCallableDynamicDoc.__call__[0;34m(self, *args, **kwds)[0m
[1;32m    262[0m [38;5;28;01mdef[39;00m [38;5;21m__call__[39m([38;5;28mself[39m, [38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds) [38;5;241m-[39m[38;5;241m>[39m T:
[0;32m--> 263[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m[38;5;18m__func__[39m([38;5;241m*[39margs, [38;5;241m*[39m[38;5;241m*[39mkwds)

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/_config/config.py:156[0m, in [0;36m_set_option[0;34m(*args, **kwargs)[0m
[1;32m    153[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124mf[39m[38;5;124m'[39m[38;5;124m_set_option() got an unexpected keyword argument [39m[38;5;124m"[39m[38;5;132;01m{[39;00mkwarg[38;5;132;01m}[39;00m[38;5;124m"[39m[38;5;124m'[39m)
[1;32m    155[0m [38;5;28;01mfor[39;00m k, v [38;5;129;01min[39;00m [38;5;28mzip[39m(args[::[38;5;241m2[39m], args[[38;5;241m1[39m::[38;5;241m2[39m]):
[0;32m--> 156[0m     key [38;5;241m=[39m _get_single_key(k, silent)
[1;32m    158[0m     o [38;5;241m=[39m _get_registered_option(key)
[1;32m    159[0m     [38;5;28;01mif[39;00m o [38;5;129;01mand[39;00m o[38;5;241m.[39mvalidator:

File [0;32m~/anaconda3/lib/python3.11/site-packages/pandas/_config/config.py:123[0m, in [0;36m_get_single_key[0;34m(pat, silent)[0m
[1;32m    121[0m     [38;5;28;01mraise[39;00m OptionError([38;5;124mf[39m[38;5;124m"[39m[38;5;124mNo such keys(s): [39m[38;5;132;01m{[39;00m[38;5;28mrepr[39m(pat)[38;5;132;01m}[39;00m[38;5;124m"[39m)
[1;32m    122[0m [38;5;28;01mif[39;00m [38;5;28mlen[39m(keys) [38;5;241m>[39m [38;5;241m1[39m:
[0;32m--> 123[0m     [38;5;28;01mraise[39;00m OptionError([38;5;124m"[39m[38;5;124mPattern matched multiple keys[39m[38;5;124m"[39m)
[1;32m    124[0m key [38;5;241m=[39m keys[[38;5;241m0[39m]
[1;32m    126[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m silent:

[0;31mOptionError[0m: Pattern matched multiple keys
OptionError: Pattern matched multiple keys

